### ISSUE TITLE
Add 4 more fields in the "join us" page form 

### ISSUE THREAD

**Issue by sceptejas** [sceptejas/Robolution#4]
Add 4 more fields in the "join us" page form, labeled "phone number" "email" "telegram id" "UTR number"

**Comment by Builder-Byte** [comment]
On it

**Comment by Nivedita-Chhokar** [comment]
can i be assigned?

**Comment by Pariyul** [comment]
hey I want to do this kindly assign this to me

**Comment by sceptejas** [comment]
@Pariyul @Nivedita-Chhokar I've assigned the issue to both of you the i'll merge the earliest pr that works.

**Comment by Pariyul** [comment]
Hey can you please tell me the labels 
because earlier ones were already done
