### ISSUE TITLE
Logo update

### ISSUE THREAD

**Issue by sceptejas** [sceptejas/Robolution#5]
Update the logo in the contact section to be consistent with the rest of the site !

**Comment by prashantrai-30** [comment]
Hey @sceptejas ,
Can you assign this to me :)

**Comment by sceptejas** [comment]
@prashantrai-30 there you go ! sorry for the delays :)

**Comment by Pariharx7** [comment]
Hey!
Can i work on this issue?

**Comment by prashantrai-30** [comment]
@sceptejas you can assign this issue to @Pariharx7 :)

**Comment by Pariharx7** [comment]
You can do it if you are already working in it @prashantrai-30

**Comment by sceptejas** [comment]
there u go !

**Comment by Pariharx7** [comment]
@sceptejas  do i need to make a logo about Robolution-beta or need to keep it same as in Robolution-beta homepage

**Comment by sceptejas** [comment]
The later, make it the same as rest of the pages
